words:
  - astrojs
  - Collabora
  - Dockerhub
  - downscaling
  - hyperconverged
  - Jagr
  - Jailman
  - Jellyfin
  - Kjeld
  - Merch
  - Minio
  - Nextcloud
  - Noob
  - ornias
  - pagefind
  - Photoprism
  - Pihole
  - preconfigured
  - Schouten
  - shadofall
  - shoutout
  - showstealers
  - Syncthing
  - TCCR
  - templating
  - Traefik
  - truecharts
  - upscaling
  - Vaultwarden
  - Xsystems
