name: Cloudflare Pages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: ${{ github.ref == 'refs/heads/main' && '(Production)' || '(Preview)' }} Publish to Cloudflare Pages
    steps:
      - name: Comment deploy start
        if: github.event_name != 'push'
        uses: mshick/add-pr-comment@v2
        with:
          message-id: cloudflare-deploy
          message: |
            ### <span aria-hidden="true">🚧</span> Deploy Preview building...

            |  Name                                               | Link                                                                                |
            |-----------------------------------------------------|-------------------------------------------------------------------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit     | ${{ github.sha }}                                                                   |
            |<span aria-hidden="true">🔍</span> Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            ---

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          # This is needed for the "last updated" field to update correctly.
          fetch-depth: 0

      - name: Setup Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          # Cache for build and optimized images.
          key: astro
          path: ./.astro

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }} # TODO:
          accountId: ${{ secrets.CF_ACCOUNT_ID }} # TODO:
          # By default Cloudflare marks `main` as the "production" branch.
          # So when this workflow is pushed to refs/heads/main, we set the branch to `main`/"production".
          branch: ${{ github.ref == 'refs/heads/main' && 'main' || github.head_ref }}
          # The project name in Cloudflare
          projectName: chart-docs # TODO:
          directory: ./build
          wranglerVersion: "3"

      - name: Comment deploy url
        uses: mshick/add-pr-comment@v2
        with:
          message-id: cloudflare-deploy
          message: |
            ### <span aria-hidden="true">✅</span> Deploy Preview ready!

            |  Name                                                | Link                                                                                |
            |------------------------------------------------------|-------------------------------------------------------------------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit      | ${{ github.sha }}                                                                   |
            |<span aria-hidden="true">🔍</span> Latest deploy log  | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            |<span aria-hidden="true">😎</span> Deploy Preview Url | [${{ steps.cloudflare.outputs.url }}](${{ steps.cloudflare.outputs.url }})          |
            |<span aria-hidden="true">🌳</span> Environment        | ${{ steps.cloudflare.outputs.environment }}                                         |
            ---
